# coding: utf-8
import uiautomator2 as ut2
import time
#登录+登录修改密码+下单+邀请码+下单
package_namesaler = 'winretailsaler.net.winchannel.wincrm'
d = ut2.connect_wifi("192.168.253.8:7912")
d.app_start(package_namesaler)
time.sleep(2)
d(text=u"登录").click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/et_username").set_text("14036958563")
d(resourceId="winretailsaler.net.winchannel.wincrm:id/et_pwd").set_text("aa123321")
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_login").click()
time.sleep(2)
d.press("back")
time.sleep(4)
d(resourceId="winretailsaler.net.winchannel.wincrm:id/win_dialog_left_btn").click_exists(timeout=5.0)
d(resourceId="winretailsaler.net.winchannel.wincrm:id/component_maintab_tab_textview", text=u"我的").click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/back").click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/imageview").click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/modify_pwd_edv_old_pwd").set_text("aa123321")
d(resourceId="winretailsaler.net.winchannel.wincrm:id/modify_pwd_edv_pwd1").set_text("aaa123321")
d(resourceId="winretailsaler.net.winchannel.wincrm:id/modify_pwd_edv_pwd2").set_text("aaa123321")
d(resourceId="winretailsaler.net.winchannel.wincrm:id/modify_pwd_btv_modify").click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/win_dialog_one_btn").click()
time.sleep(3)
d(text=u"登录").click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/et_username").set_text("14036958563")
d(resourceId="winretailsaler.net.winchannel.wincrm:id/et_pwd").set_text("aaa123321")
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_login").click()
time.sleep(3)
d.press("back")
d(resourceId="winretailsaler.net.winchannel.wincrm:id/win_dialog_left_btn").click_exists(timeout=5.0)
print("登录成功+登录修改密码+下单+邀请码+下单")
time.sleep(2)
for i in range(3):
    d.swipe(300, 1700, 300, 300)
d(resourceId="winretailsaler.net.winchannel.wincrm:id/item_brand_bg", className="android.widget.ImageView", instance=1).click()
time.sleep(2)
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_increase").click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_increase").click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_increase").click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_increase", className="android.widget.TextView", instance=1).click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_increase", className="android.widget.TextView", instance=1).click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_increase", className="android.widget.TextView", instance=1).click()
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_ok").click()
time.sleep(2)
d(resourceId="winretailsaler.net.winchannel.wincrm:id/btn_ok").click()
time.sleep(2)
d(resourceId="winretailsaler.net.winchannel.wincrm:id/et_code").set_text("14025639874")
time.sleep(2)
d.press("back")
d(resourceId="winretailsaler.net.winchannel.wincrm:id/et_message").set_text("558789")
d.press("back")
time.sleep(2)
d(resourceId="winretailsaler.net.winchannel.wincrm:id/ok_button").click()
time.sleep(2)
d(resourceId="winretailsaler.net.winchannel.wincrm:id/rightbtn").click()
time.sleep(2)
d.press("back")
time.sleep(2)
d.press("back")
