# coding=utf8
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
from method import *
from selenium import webdriver

driver = webdriver.Firefox()
class coupon():
    inventory = public_method(driver)
    title = []
    #惠下单满减订单无限制
    def unliMited_Order(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"惠下单满减无限制")
        time.sleep(2)
        # 仅限移动支付
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        time.sleep(1)
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"惠满减无")
        sel = dr.find_element_by_id("exclusiveCategory")
        Select(sel).select_by_value('3')
        # 订单
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('1')
        dr.find_element_by_css_selector("#memoId").send_keys(u"惠下单满减无限制")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"230")
        dr.find_element_by_css_selector("#scoreId").send_keys(u"20")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(3)
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_2()

    #优惠券满减订单优惠券类型排他
    def  mold_Order(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"惠下单满减优惠券类型排他")
        time.sleep(2)
        # 仅限移动支付
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        time.sleep(1)
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"惠减优排")
        sel = dr.find_element_by_id("exclusiveCategory")
        Select(sel).select_by_value('2')
        # 订单
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('1')
        dr.find_element_by_css_selector("#memoId").send_keys(u"惠下单满减优惠券类型排他")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"165")
        dr.find_element_by_css_selector("#scoreId").send_keys(u"8")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(3)
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_2()

    #惠下单满减订单全排它
    def exclusion_Order(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"惠下单满减全排他")
        time.sleep(2)
        # 仅限移动支付
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        time.sleep(1)
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"惠减全排")
        sel = dr.find_element_by_id("exclusiveCategory")
        Select(sel).select_by_value('0')
        # 订单
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('1')
        dr.find_element_by_css_selector("#memoId").send_keys(u"惠下单满减全排他")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"155")
        dr.find_element_by_css_selector("#scoreId").send_keys(u"15")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(2)
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_2()

    #惠下单满减订单无门槛
    def threshold_Order(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"惠下单满减无门槛")
        time.sleep(2)
        # 仅限移动支付
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        time.sleep(1)
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"惠满减槛")
        sel = dr.find_element_by_id("exclusiveCategory")
        Select(sel).select_by_value('4')
        # 订单
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('1')
        dr.find_element_by_css_selector("#memoId").send_keys(u"惠下单满减无门槛")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"190")
        dr.find_element_by_css_selector("#scoreId").send_keys(u"17")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(3)
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_2()

    #供应商满减订单出资方排他
    def supplier_Order(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"供应商满减")
        time.sleep(2)
        # 仅限移动支付
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        time.sleep(1)
        #供应商
        sel = dr.find_element_by_id("src")
        Select(sel).select_by_value('2')
        dr.find_element_by_id("poiDealerName").click()
        time.sleep(2)
        current_window = dr.current_window_handle  # 获取当前窗口handle name
        all_windows = dr.window_handles  # 获取所有窗口handle name
        for window in all_windows:
            if window != current_window:
                dr.switch_to.window(window)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.switch_to.frame("modalDialog")
        dr.switch_to.frame("tree")
        dr.find_element_by_xpath(".//*[@id='searchbox']/table/tbody/tr/td[4]/input").send_keys(u"惠经商37号")
        dr.find_element_by_id("query_A").click()
        dr.find_element_by_xpath(".//*[@id='poiDealerList_table']/tbody/tr/td[1]/input").click()
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(2)").click()
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_id("couponLabel").send_keys(u"供应满减")
        sel = dr.find_element_by_id("exclusiveCategory")
        Select(sel).select_by_value('1')
        # 订单
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('1')
        dr.find_element_by_css_selector("#memoId").send_keys(u"好啊好啊哈哈")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"140")
        dr.find_element_by_css_selector("#scoreId").send_keys(u"13")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(3)
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_2()
    #品牌商满减订单
    def brand_Order(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"品牌满减")
        time.sleep(2)
        # 仅限移动支付
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        time.sleep(1)
        sel = dr.find_element_by_id("src")
        Select(sel).select_by_value('1')
        dr.find_element_by_xpath(".//*[@id='s2id_poiBrandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen1_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        # 订单
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('1')
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"品牌满减")
        dr.find_element_by_css_selector("#memoId").send_keys(u"品牌满减")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"150")
        dr.find_element_by_css_selector("#scoreId").send_keys(u"13")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(2)
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_2()

    #惠下单满减指定商品范围
    def voucher_Scopen(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"范围内满减")
        time.sleep(2)
        # 仅限移动支付
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        time.sleep(1)
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"范围满减")
        # 范围满减
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('5')
        dr.find_element_by_id("couponSubType").send_keys(u"范围满减")
        dr.find_element_by_css_selector("#memoId").send_keys(u"范围内满减")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"160")
        dr.find_element_by_css_selector("#scoreId").send_keys(u"9")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(2)
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_4()
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[3]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_2()

    #惠下单按件赠系列
    def piece(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"按件赠送")
        time.sleep(2)
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"按件赠送")
        # 满赠
        sel = dr.find_element_by_xpath("//select[@id='couponType']")
        Select(sel).select_by_value('5')
        time.sleep(1)
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('4')
        time.sleep(1)
        dr.find_element_by_id("couponSubType").send_keys(u"功能饮料")
        dr.find_element_by_css_selector("#memoId").send_keys(u"按键赠啊")
        dr.find_element_by_css_selector("#giftDesc").send_keys(u"按键赠啊")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"4")
        sel = dr.find_element_by_id("bonusConditionType")
        Select(sel).select_by_value('2')
        dr.find_element_by_css_selector("#scoreId").send_keys(u"10")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(2)
        # 设置赠品
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_3()
        # 设置区域
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[3]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_2()

    #惠下单按件减商品
    def reduction(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"按键减哈")
        time.sleep(2)
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"按键减哈")
        # 按键减
        sel = dr.find_element_by_id("couponType")
        Select(sel).select_by_value('4')
        time.sleep(1)
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('3')
        dr.find_element_by_css_selector("#memoId").send_keys(u"老铁老铁")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"3")
        sel = dr.find_element_by_id("bonusConditionType")
        Select(sel).select_by_value('2')
        dr.find_element_by_css_selector("#scoreId").send_keys(u"17")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()

    # 设置区域
        time.sleep(2)
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_2()

    #惠下单满赠品牌
    def gifts(self):
        dr = driver
        dr.implicitly_wait(10)
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"哈哈满赠")
        time.sleep(2)
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"满赠呵呵")
        # 满赠
        sel = dr.find_element_by_xpath("//select[@id='couponType']")
        Select(sel).select_by_value('2')
        time.sleep(1)
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('2')
        dr.find_element_by_css_selector("#memoId").send_keys(u"你好你好")
        dr.find_element_by_css_selector("#giftDesc").send_keys(u"开心吗伙计")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"180")
        # dr.find_element_by_css_selector("#scoreId").send_keys(u"12")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(2)
        #设置赠品
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_3()
        #设置区域
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[3]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_2()

    #惠下单满减订单
    def voucher(self):
        dr = driver
        dr.implicitly_wait(10)
        # url = "http://uat.wincrm.net:8218"
        url = "http://retail.wincrm.net:8203"
        dr.get(url)
        # dr.find_element_by_css_selector("#userAccount").send_keys("winretailsaler")
        dr.find_element_by_css_selector("#userAccount").send_keys("zhangkesaler")

        # dr.find_element_by_css_selector("input.login_pwd").send_keys("win!@#")
        dr.find_element_by_css_selector("input.login_pwd").send_keys("11111111")
        dr.find_element_by_css_selector("li.login_on>a").click()
        dr.find_element_by_css_selector("#menuId_hxdplatform").click()
        dr.switch_to.frame("menu1")
        time.sleep(2)
        dr.maximize_window()
        dr.find_element_by_css_selector("div.promptHeader>a").click()
        time.sleep(2)
        for i in range(1, 5):
            dr.find_element_by_xpath(".//*[@id='menuScrollAuto']").send_keys(Keys.DOWN)
        dr.find_element_by_link_text("促销管理").click()
        dr.find_element_by_css_selector("#a_menuId_yhqmbgl").click()
        time.sleep(2)
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        dr.find_element_by_css_selector("div.MenuList>a:nth-child(3)").click()
        dr.find_element_by_xpath(".//*[@id='titleId']").send_keys(u"嘿嘿满减")
        time.sleep(2)
        #仅限移动支付
        sel = dr.find_element_by_xpath(".//*[@id='SollAuto']/div/table/tbody/tr[3]/td[2]/select")
        Select(sel).select_by_value('2')
        time.sleep(1)
        #订单
        sel = dr.find_element_by_id("couponConditionType")
        Select(sel).select_by_value('1')
        dr.find_element_by_xpath(".//*[@id='couponLabel']").send_keys(u"满减嘿嘿")
        dr.find_element_by_css_selector("#memoId").send_keys(u"我的我的哈哈")
        for i in range(1, 4):
            dr.find_element_by_css_selector("div.sheet_div").send_keys(Keys.DOWN)
        dr.find_element_by_css_selector("#priceId").send_keys(u"110")
        dr.find_element_by_css_selector("#scoreId").send_keys(u"12")
        dr.find_element_by_xpath(".//*[@id='s2id_brandCode']/a/span[2]/b").click()
        dr.find_element_by_css_selector("input#s2id_autogen2_search").send_keys(u"脉动")
        time.sleep(1)
        dr.find_element_by_css_selector("span.select2-match").click()
        dr.find_element_by_css_selector("#doModifyId").click()
        time.sleep(1)
        dr.switch_to.alert.accept()
        time.sleep(2)
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[2]").click()
        time.sleep(2)
        self.inventory.method_1()
        dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[3]/center/a[1]").click()
        time.sleep(2)
        self.inventory.method_2()
        dr.switch_to.default_content()
        dr.switch_to.frame("main1")
        time.sleep(2)
        llo = dr.find_element_by_xpath(".//*[@id='ec_table']/tbody/tr[1]/td[15]").text
        self.title.append(llo)



